version: '3'
services:
  db:
    container_name: chatter_backend_db
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: {}
